//
// This is the base configuration file for ORR Portal web application.
// Do not edit this file. Instead, define/override properties for your particular
// instance in a sibling file with name 'local.config.js'. In that file, use the
// full path of the properties that need to be defined, for example:
//   appConfig.branding.logo = "https://example.net/my-logo.png";
//   appConfig.orront.rest   = "https://example.net/ont";
//

var appConfig = {
  help: "https://mmisw.github.io/mmiorr-docs/",

  portal: {
    // (required) main ORR page URL.
    // This can start with '//' to dynamically accommodate http or https access.
    mainPage: "//example.net/ont/"
  },

  orront: {
    // (required) orr-ont endpoint URL. (No trailing slash.)
    // This could be a full URL ("https://example.net/ont")
    // or a path relative to the orr-portal host ("/ont")
    rest: "/ont",

    // (required) SPARQL endpoint URL.  (No trailing slash.)
    // This could be a full URL ("https://example.net/sparql")
    // or a path relative to the orr-portal host ("/sparql")
    sparqlEndpoint: '/sparql'
  },

  branding: {
    // (optional) URL of image to show in the page header.
    // By default, this will be MMI ORR's logo.
    //logo: "http://cor.esipfed.org/orr/images/logo.png"

    // (optional) string used for <head><title> in main pages.
    // By default, this will be related with the MMI ORR.
    //title: "ESIP Community Ontology Repository"

    // (optional) "Terms of Use" link.
    // No default value.
    //tou: "http://somewhere/mytermsofuse"
  }

  // (required) firebase application.
  // NOTE: This may be removed in a future version.
  ,firebase: {
    url: "https://[myapp].firebaseio.com"
  }
};
